'use strict';

module.exports = (sequelize, DataTypes) => {
    var Order = sequelize.define('order', {
        OrderID: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        OrderStatus: DataTypes.INTEGER,
        UserID: DataTypes.INTEGER,
        RestID: DataTypes.INTEGER,
        Instructions: DataTypes.STRING,
        TotalItems: DataTypes.INTEGER,
        RestSubTotal: DataTypes.DECIMAL,
        CustSubTotal: DataTypes.DECIMAL,
        RestDiscount: DataTypes.DECIMAL,
        TotalDiscount: DataTypes.DECIMAL,
        Wallet: DataTypes.INTEGER,
        RestComission: DataTypes.DECIMAL,
        DiscountCode: DataTypes.STRING,
        DeliveryCharge: DataTypes.DECIMAL,
        Tax: DataTypes.DECIMAL,
        RestTax: DataTypes.DECIMAL,
        PenaltyPaid: DataTypes.DECIMAL,
        CustTotal: DataTypes.DECIMAL,
        RestTotal: DataTypes.DECIMAL,
        PayCash: DataTypes.BOOLEAN,
        DLabel: DataTypes.STRING,
        DAddress: DataTypes.STRING,
        DLatitude: DataTypes.STRING,
        DLongitude: DataTypes.STRING,
        DeliveryUserID: DataTypes.INTEGER,
        DeviceType: DataTypes.STRING,
        PickUpOTP: DataTypes.INTEGER,
        DeliveryOTP: DataTypes.INTEGER,
        PickedOn: DataTypes.DATE,
        DeliveredOn: DataTypes.DATE,
        DeliveryRating: DataTypes.DECIMAL,
        MealRating: DataTypes.DECIMAL,
        Taste: DataTypes.BOOLEAN,
        Packaging: DataTypes.BOOLEAN,
        Portion: DataTypes.BOOLEAN,
        MealSuggestion: DataTypes.STRING,
        Behaviour: DataTypes.BOOLEAN,
        Time: DataTypes.BOOLEAN,
		PreparationTime: DataTypes.TIME,
		ConformationTime: DataTypes.TIME,
        Timer: DataTypes.TIME, 
        ConfOrdAt: DataTypes.TIME,
        Handling: DataTypes.BOOLEAN,
        DeliverySuggestion: DataTypes.STRING,
        Question1: DataTypes.INTEGER,
        Question2: DataTypes.INTEGER,
        Question3: DataTypes.INTEGER,
        Active: DataTypes.BOOLEAN,
        PaidToRestaurant: DataTypes.BOOLEAN,
        CancelledOn: DataTypes.DATE,
        CancelledBy: DataTypes.INTEGER,
        invoice_pdf: DataTypes.TEXT,
    }, {
        tableName: 'tblOrders',
        createdAt: 'CreatedOn',
        updatedAt: false
    });

    return Order;
};
